theme: minima
title: The Titleist Title
author: Me Me Me
email: my-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is a test / tutorial brought to you by github.
  It goes on and on and on.

# social links
twitter_username: my-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  my-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
