theme: minima
skin: solarized
title: Project Title
author:
  name: Me Me Me
  email: my-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is a test / tutorial brought to you by github.
  It goes on and on and on.
header_pages:
  - about.md
  - architecture.md

minima:
  social links:
    # twitter: my-twitter-handle # DO NOT include the @ character, or else the build will fail!
    # github:  my-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
